"""empty message

Revision ID: 42803991220b
Revises: 79af246a4839
Create Date: 2025-11-07 17:57:57.884682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42803991220b'
down_revision = '79af246a4839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biblioteca_usuario', schema=None) as batch_op:
        batch_op.drop_column('progreso_lectura')

    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.alter_column('calificacion',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.alter_column('calificacion',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('biblioteca_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progreso_lectura', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
