"""Add reading state to UserLibrary

Revision ID: 79af246a4839
Revises: 
Create Date: 2025-11-05 21:56:29.746624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79af246a4839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('biblioteca_usuario', schema=None) as batch_op:

        batch_op.add_column(sa.Column('estado_lectura', sa.String(length=20), 
                                       server_default='quiero_leer', nullable=False))
        batch_op.add_column(sa.Column('progreso_lectura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), 
                                       server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biblioteca_usuario', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('estado_lectura')

    # ### end Alembic commands ###